defaultProject: edgar-ai
defaultLocation: us-central1
defaultDataset: edgar2
defaultAssertionDataset: dataform_assertions
dataformCoreVersion: 3.0.0
vars:
  embedding_dimensionality: "768"
  cloud_func_connection: us-central1.cloud-funcs
  vertexai_connection: us-central1.ai1
  # num of companies to sample
  cik_samples: "100"
  # when set to true, will limit rows in some query to reduce the run time
  debug: "false"
  # path for json file export, uri for a GS bucket, do not put / at the end
  json_export_prefix: "gs://edgar_666/bq_export"
